Repository test-devf-merge/merge-bot-experiment, pull requests merged in 2019-02, with the labels that each got.

#93 Create a1
  a1
Labels: ready-to-merge, size/XS

#95 Create a3
  a3
Labels: ready-to-merge, size/XS

#96 Create a4
  a4
Labels: ready-to-merge, size/XS

#97 Create a5
  a5
Labels: ready-to-merge, size/XS

#98 Create 001
  andres/001
Labels: ready-to-merge, size/XS

#99 Create 002
  andres/002
Labels: ready-to-merge, size/XS

#101 Create z2
  z2
Labels: ready-to-merge, size/XS

#102 Create z3
  z3
Labels: ready-to-merge, size/XS

#103 Create z4
  z4
Labels: ready-to-merge, size/XS

#104 Create z5
  z5
Labels: ready-to-merge, size/XS

#100 Create z1
  z1
Labels: ready-to-merge, size/XS

#105 Create z6
  z6
Labels: ready-to-merge, size/XS

#126 Create 001
  andres/001
Labels: ready-to-merge, size/XS

#128 Create 003
  andres/003
Labels: ready-to-merge, size/XS

#127 Create 002
  andres/002
Labels: ready-to-merge, size/XS

#129 Create 004
  andres/004
Labels: ready-to-merge, size/XS

#130 Create 005
  andres/005
Labels: ready-to-merge, size/XS

#131 Create 006
  andres/006
Labels: ready-to-merge, size/XS

#123 Create 5
  5
Labels: ready-to-merge, size/XS

#119 Create 1
  1
Labels: ready-to-merge, size/XS

#121 Create 3
  3
Labels: ready-to-merge, size/XS

#122 Create 4
  4
Labels: size/XS

#125 Create ttt
  ttt
Labels: size/XS

#132 Create tide-01
  andres/tide-01
Labels: ready-to-merge, size/XS

#133 Create asd
  asd
Labels: ready-to-merge, size/XS

#134 Create qqq
  qqq
Labels: ready-to-merge, size/XS

#135 Create www
  www
Labels: ready-to-merge, size/XS

#136 Create sss
  sss
Labels: ready-to-merge, size/XS

#137 Create ddd
  ddd
Labels: ready-to-merge, size/XS

#138 Create ggg
  ggg
Labels: ready-to-merge, size/XS

#139 Create hhh
  hhh
Labels: ready-to-merge, size/XS

#140 Create test-merge-01
  andres/test-merge-01
Labels: ready-to-merge
