Repository test-devf-merge/merge-bot-experiment, pull requests merged in 2019-01, with the labels that each got.

#22 Create andres-001
  andres-001
Labels: ready-to-merge, size/XS

#24 Create andres 003
  andres 003
Labels: ready-to-merge, size/XS

#25 Create multi-001
  multi-001
Labels: ready-to-merge, size/XS

#27 Create multi-003
  multi-003
Labels: ready-to-merge, size/XS

#28 Create multi-004
  multi-004
Labels: ready-to-merge, size/XS

#29 Create multi-005
  multi-005
Labels: ready-to-merge, size/XS

#26 Create multi-002
  multi-002
Labels: ready-to-merge, size/XS

#32 Create 12.txt
  12.txt
Labels: ready-to-merge, size/XS

#33 Create 13.txt
  13.txt
Labels: ready-to-merge

#35 Create 15.txt
  15.txt
Labels: ready-to-merge

#39 Create 16.txt
  16.txt
Labels: ready-to-merge, size/XS

#41 Create 18.txt
  18.txt
Labels: ready-to-merge, size/XS

#34 Create 14.txt
  14.txt
Labels: ready-to-merge

#42 Create 31.txt
  31.txt
Labels: ready-to-merge, size/XS

#43 Create 32.txt
  32.txt
Labels: ready-to-merge, size/XS

#45 Create moving-master
  moving-master
Labels: ready-to-merge, size/XS

#30 Create 11.txt
  11.txt
Labels: ready-to-merge, size/S

#36 Create 20.txt
  20.txt
Labels: ready-to-merge, size/XS

#48 Create 112
  112
Labels: size/XS

#46 Create 110
  110
Labels: ready-to-merge, size/XS

#53 Create 115
  115
Labels: ready-to-merge, size/XS

#54 Create 116
  116
Labels: kind/bug, ready-to-merge, size/XS

#56 Create 202.txt
  202.txt
Labels: ready-to-merge, size/XS

#66 Create 313.txt
  313.txt
Labels: ready-to-merge, size/XS

#63 Create 310.txt
  310.txt
Labels: ready-to-merge, size/XS

#65 Create 312.txt
  312.txt
Labels: ready-to-merge, size/XS

#64 Create 311.txt
  311.txt
Labels: ready-to-merge, size/XS

#67 Create 314.txt
  314.txt
Labels: ready-to-merge, size/XS

#68 Mskonovalov patch 9
  q1.txt
Labels: ready-to-merge, size/XS

#31 Create test-101
  test-101
Labels: ready-to-merge, size/XS

#69 Mskonovalov patch 10
  q2.txt
Labels: ready-to-merge, size/XS

#75 Create w3
  w3
Labels: ready-to-merge, size/XS

#73 Create w1
  w1
Labels: ready-to-merge, size/XS

#76 Create w4
  w4
Labels: ready-to-merge, size/XS

#77 Create w5
  w5
Labels: ready-to-merge, size/XS

#78 Create e1
  e1
Labels: ready-to-merge, size/XS

#80 Create e3
  e3
Labels: ready-to-merge, size/XS

#81 Create e4
  e4
Labels: ready-to-merge, size/XS

#82 Create e5
  e5
Labels: ready-to-merge, size/XS

#83 Create r1
  r1
Labels: ready-to-merge, size/XS

#84 Create r2
  r2
Labels: ready-to-merge, size/XS

#85 Create r3
  r3
Labels: ready-to-merge, size/XS

#86 Create r4
  r4
Labels: ready-to-merge, size/XS

#87 Create r5
  r5
Labels: ready-to-merge, size/XS

#88 Create t1
  t1
Labels: ready-to-merge, size/XS

#89 Create t2
  t2
Labels: ready-to-merge, size/XS

#90 Create t3
  t3
Labels: ready-to-merge, size/XS

#91 Create t4
  t4
Labels: ready-to-merge, size/XS

#92 Create t5
  t5
Labels: ready-to-merge, size/XS
